import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Refuture",
  description: "Generated by create next app",
  icons: {
    icon: '/refuture.ico', // using the refuture icon from app directory
    shortcut: '/refuture.ico',
    apple: '/refuture.ico', // for iOS devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
